services:
  chat-db:
    image: 'chat-db:latest'
    ports:
      - '5432:5432'
    networks:
      - chat-network
    environment:
      - POSTGRES_PASSWORD=postgres
    command:
      - postgres
      - '-c'
      - wal_level=logical
    healthcheck:
      test:
        - CMD
        - psql
        - '-U'
        - postgres
        - '-c'
        - SELECT 1
      interval: 10s
      timeout: 5s
      retries: 5

  chat-kafka:
    image: 'confluentinc/cp-kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
      - '29092:29092'
    depends_on:
      chat-db:
        condition: service_healthy
    networks:
      - chat-network
    environment:
      KAFKA_KRAFT_MODE: 'true'
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://chat-kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: Mk3OEYBSD34fcwNTJENDM2Qk
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
      
  debezium:
    image: 'quay.io/debezium/connect:latest'
    restart: always
    networks:
      - chat-network
    depends_on:
      chat-db:
        condition: service_healthy
      chat-kafka:
        condition: service_healthy
    ports:
      - '8083:8083'
    environment:
      BOOTSTRAP_SERVERS: 'chat-kafka:9092'
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      STATUS_STORAGE_TOPIC: connect_statuses
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      ENABLE_DEBEZIUM_SCRIPTING: 'true'
    healthcheck:
      test:
        - CMD
        - curl
        - '--silent'
        - '--fail'
        - '-X'
        - GET
        - 'http://localhost:8083/connectors'
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
      
  schema-registry:
    image: 'confluentinc/cp-schema-registry:latest'
    depends_on:
      chat-kafka:
        condition: service_healthy
    ports:
      - '8081:8081'
    networks:
      - chat-network
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://chat-kafka:9092'
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
    healthcheck:
      test:
        - CMD
        - curl
        - '--silent'
        - '--fail'
        - 'http://localhost:8081/subjects'
      interval: 10s
      timeout: 5s
      retries: 5
      
  ksqldb-server:
    image: confluentinc/ksqldb-server:latest
    depends_on:
      chat-kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    ports:
      - "8088:8088"
    networks:
      - chat-network
    environment:
      KSQL_BOOTSTRAP_SERVERS: "chat-kafka:9092"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: "0"
      KSQL_KSQL_SERVICE_ID: "ksql_"
      KSQL_INTERNAL_TOPIC_REPLICAS: 1
    healthcheck:
      test:
        - CMD
        - curl
        - '--silent'
        - '--fail'
        - 'http://localhost:8088/info'
      interval: 10s
      timeout: 5s
      retries: 5
      
  control-center:
    image: 'confluentinc/cp-enterprise-control-center:latest'
    depends_on:
      chat-kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      ksqldb-server:
        condition: service_healthy
    ports:
      - '9021:9021'
    networks:
      - chat-network
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'chat-kafka:9092'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONTROL_CENTER_KSQL_KSQLDB_URL: 'http://ksqldb-server:8088'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
    healthcheck:
      test:
        - CMD
        - curl
        - '--silent'
        - '--fail'
        - 'http://localhost:9021'
      interval: 10s
      timeout: 5s
      retries: 5
      
  vue-chat-api:
    image: vue-chat-api:latest
    depends_on:
      control-center:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - chat-network
    environment:
      REACTIVE_POSTGRES_URL: "r2dbc:postgresql://chat-db:5432/postgres"
      POSTGRES_URL: "jdbc:postgresql://chat-db:5432/postgres"
      DEBEZIUM_URL: "http://debezium:8083/connectors"
      KAFKA_HOST: "chat-kafka:9092"
      KSQLDB_URL: "http://ksqldb-server:8088/ksql"
      
  vue-chat-web:
    image: vue-chat-web:latest
    depends_on:
      control-center:
        condition: service_healthy
    ports:
      - "5173:80"
    networks:
      - chat-network
    environment:
      VUE_APP_API_URL=: "http://localhost:8080"
      
networks:
  chat-network:
    name: chat-network

