server:
  port: 8080
  forward-headers-strategy: NATIVE
spring:
  main:
    banner-mode: off
  r2dbc:
    url: ${REACTIVE_POSTGRES_URL:r2dbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers:
    - ${KAFKA_HOST:localhost:29092}
vue-chat-api:
  configuration:
    kafkaHost: ${KAFKA_HOST:localhost:29092}
    debeziumUrl: ${DEBEZIUM_URL:http://localhost:8083/connectors}
    ksqldbUrl: ${KSQLDB_URL:http://localhost:8088/ksql}