server:
  port: 8080
  forward-headers-strategy: NATIVE
spring:
  main:
    banner-mode: off
  r2dbc:
    url: ${POSTGRES_URL:r2dbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}